services:
  jupyter:
    image: wqxxzd/raincouver-prediction-images:668c7b7
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
  