services:
  jupyter:
    image: wqxxzd/raincouver-prediction-images:58e771c
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
    environment:
      PASSWORD: password
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64